"""initial schema

Revision ID: a9e1dcce6457
Revises: 
Create Date: 2026-06-02 18:31:16.300782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e1dcce6457'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('twin_customer_ref', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('primary_phone', sa.String(), nullable=False),
    sa.Column('alt_phone', sa.String(), nullable=True),
    sa.Column('language_pref', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('twin_customer_ref')
    )
    op.create_index('idx_customers_primary_phone', 'customers', ['primary_phone'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('twin_order_ref', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('merchant', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_area', sa.Text(), nullable=True),
    sa.Column('delivery_window', sa.Text(), nullable=True),
    sa.Column('otp_code', sa.Text(), nullable=True),
    sa.Column('assigned_driver', sa.Text(), nullable=True),
    sa.Column('expected_pieces', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('twin_order_ref')
    )
    op.create_index('idx_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_table('calls',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('happyrobot_call_id', sa.Text(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.Text(), nullable=False),
    sa.Column('caller_number', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('disposition', sa.Text(), nullable=True),
    sa.Column('csat_score', sa.Numeric(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('call_id'),
    sa.UniqueConstraint('happyrobot_call_id')
    )
    op.create_index('idx_calls_order_id', 'calls', ['order_id'], unique=False)
    op.create_index('idx_calls_started_at', 'calls', ['started_at'], unique=False)
    op.create_table('address_flags',
    sa.Column('flag_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('original_address', sa.Text(), nullable=False),
    sa.Column('correction_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('flag_id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('escalations',
    sa.Column('escalation_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('escalation_id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('fallback_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('investigations',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('callback_due_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('investigation_id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('merchant_referrals',
    sa.Column('referral_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('referral_id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('reschedules',
    sa.Column('reschedule_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_window', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('synced_to_twin_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('reschedule_id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('verifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('factors_checked', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('factors_passed', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications')
    op.drop_table('reschedules')
    op.drop_table('merchant_referrals')
    op.drop_table('investigations')
    op.drop_table('fallback_messages')
    op.drop_table('escalations')
    op.drop_table('address_flags')
    op.drop_index('idx_calls_started_at', table_name='calls')
    op.drop_index('idx_calls_order_id', table_name='calls')
    op.drop_table('calls')
    op.drop_index('idx_orders_customer_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_customers_primary_phone', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
